/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package gradle.repo;

import org.junit.jupiter.api.Test;

import static org.assertj.core.api.Assertions.assertThat;

class LibraryTest {
    @Test void someLibraryMethodReturnsTrue() {
        Library classUnderTest = new Library();
        assertThat(classUnderTest.someLibraryMethod()).as("someLibraryMethod should return 'true'").isTrue();
    }
}
