---
name: publish

on:
  push:
    tags:
      - v*
permissions:
  contents: write
env:
  GRADLE_SWITCHES: --console=plain --info --warning-mode=all
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Get the TAG version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      - uses: gradle/wrapper-validation-action@v1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 19
      - name: Builds the zip file
        timeout-minutes: 20
        uses: gradle/gradle-build-action@v2.4.2
        with:
          arguments: ${{ env.GRADLE_SWITCHES }} distZip
      - name: Create a Release
        uses: softprops/action-gh-release@v1
        with:
          generate_release_notes: true
          files: ./build/distributions/moderne-connect.zip